[package]
name = "rust-snake"
version = "0.1.0"
edition = "2021"

[lib]
name = "snakelib"
crate-type = ["cdylib"]
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.86"
